services:
  web:
    container_name: meamo.web.production
    image: ${DOCKER_REGISTRY}/web:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: ops/production/Dockerfile
      target: web
    restart: always
    ports:
      - "${DOCKER_HOST:-127.0.0.1:8000}:80"
    volumes:
      - .:/opt/apps/meamo:ro
    depends_on:
      - fpm
    networks:
      - meamo

  fpm:
    container_name: meamo.fpm.production
    image: ${DOCKER_REGISTRY}/fpm:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: ops/production/Dockerfile
      target: fpm
    restart: always
    volumes:
      - .:/opt/apps/meamo
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    networks:
      - meamo

  mysql:
    container_name: meamo.mysql.production
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meamo
    command: >
      --max_connections=500
      --innodb_buffer_pool_size=4096M
      --innodb_log_file_size=256M
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - meamo

  redis:
    container_name: meamo.redis.production
    image: redis:6.0
    restart: always
    volumes:
      - redis:/data
    networks:
      - meamo

networks:
  meamo:
    driver: bridge

volumes:
  mysql:
    name: meamo.mysql.production
  redis:
    name: meamo.redis.production
